# Generated by Django 4.2 on 2023-06-06 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipeMedicale',
            fields=[
                ('numEquipe', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MembreEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('cin', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Citoyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('date_naissance', models.DateField(default='00-00-0000')),
                ('adresse', models.CharField(max_length=70)),
                ('telephone', models.CharField(max_length=13)),
                ('cin', models.CharField(max_length=10)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profil.equipemedicale')),
            ],
        ),
    ]
