# Generated by Django 4.2 on 2023-06-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citoyen',
            name='date_vaccination1',
            field=models.DateField(default='2023-01-01'),
        ),
        migrations.AddField(
            model_name='citoyen',
            name='date_vaccination2',
            field=models.DateField(default='2023-01-01'),
        ),
        migrations.AlterField(
            model_name='citoyen',
            name='date_naissance',
            field=models.DateField(default='2023-01-01'),
        ),
    ]
