# Generated by Django 4.2 on 2023-06-07 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profil', '0003_alter_citoyen_equipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citoyen',
            name='equipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Profil.equipemedicale'),
        ),
    ]
