# Generated by Django 4.2 on 2023-06-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profil', '0008_membreequipe_equipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='citoyen',
            name='utilisateur_rempli',
            field=models.BooleanField(default=False),
        ),
    ]
