# Generated by Django 4.2 on 2023-06-14 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profil', '0009_citoyen_utilisateur_rempli'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citoyen',
            old_name='utilisateur_rempli',
            new_name='profil_complete',
        ),
    ]
