# Generated by Django 4.2 on 2023-06-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profil', '0010_rename_utilisateur_rempli_citoyen_profil_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citoyen',
            name='cin',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
