# Generated by Django 4.2 on 2023-06-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profil', '0011_alter_citoyen_cin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citoyen',
            name='telephone',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
